### ISSUE TITLE
ARDUINO 1.6.5 update?

### ISSUE THREAD

**Issue by ashottonoyan** [OpenDevice/Arduino#5]
Have you stopped developing this awesome IDE? You version is still 1.6.2 compared to the latest 1.6.5 stable version.

**Comment by ricardojlrufino** [comment]
Hello,

I'm working with the Arduino team to integrate in the official version

**Comment by ashottonoyan** [comment]
That's awesome! Arduino.cc or arduino.org team?

Cheers,
Ashot

**Comment by ricardojlrufino** [comment]
Arduino.cc

**Comment by ashottonoyan** [comment]
cool

**Comment by JackArduino** [comment]
the Arduino.cc has release the 1.9 beta with auto-complete function but it not work well as yours edited IDE, i think that you shuould develop an version for every offical ide relase version. Cheer!!
